### ISSUE TITLE
Discord Link doesnt work

### ISSUE THREAD

**Issue by r00bit1984** [AnnikenYT/SduiAPI#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by r00bit1984** [comment]
yeah sorry you needed to open in new tab, just clicking on it wouldn't work

**Comment by AnnikenYT** [comment]
Thank you very much, since this library isn't maintained anymore in favour of the [JavaScript Library](https://github.com/AnnikenYT/sdui-sdk-js) I forgot to update the discord link 😅

**Comment by AnnikenYT** [comment]
> yeah sorry you needed to open in new tab, just clicking on it wouldn't work

Wouldn't have worked, the link was outdated.

**Comment by r00bit1984** [comment]
ahh i see, you just updated it really quickly, thanks!
